#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Secret
metadata:
  name: logstash
  namespace: observability
type: Opaque
data:
  dd_api_key: #@ base64.encode(data.values.dd_api_key)